# Generated by Django 5.2.7 on 2025-10-22 06:47

import apps.common.utils
import apps.common.validators
import django.core.validators
import django.db.models.deletion
import django_clamd.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(max_length=200, verbose_name='Название контракта')),
                ('document', models.FileField(blank=True, null=True, upload_to=apps.common.utils.create_dynamic_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), apps.common.validators.FileSizeValidator(max_size_mb=10), django_clamd.validators.validate_file_infection], verbose_name='Файл с документом')),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сумма')),
                ('start_date', models.DateField(db_index=True, verbose_name='Дата заключения')),
                ('end_date', models.DateField(db_index=True, verbose_name='Дата окончания')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='products.service', verbose_name='Предоставляемая услуга')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
                'ordering': ['-start_date'],
            },
        ),
    ]
