# Generated by Django 5.2.7 on 2025-10-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeclient',
            name='potential_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_history', to='leads.potentialclient', verbose_name='Потенциальный клиент'),
        ),
    ]
