# =========================================================================
# Конфигурация pre-commit хуков
# =========================================================================

# Список репозиториев, из которых будут взяты хуки.
repos:
  # -------------------------------------------------------------------------
  # Репозиторий с базовыми хуками, которые полезны для любого проекта.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Предотвращает коммит файлов с маркерами конфликтов слияния
      - id: check-merge-conflict
      # Проверяет синтаксис YAML файлов.
      - id: check-yaml
      # Проверяет синтаксис JSON файлов.
      - id: check-json
      # Проверяет синтаксис TOML файлов.
      - id: check-toml
      # Убирает лишние пробелы в конце строк.
      - id: trailing-whitespace
      # Предотвращает коммит больших файлов (можно настроить args)
      - id: check-added-large-files
      # Ищет приватные ключи
      - id: detect-private-key

  # -------------------------------------------------------------------------
  # Хуки для Ruff.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      # Запуск линтера (аналог `ruff check --fix`).
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]  # Автоматически исправлять и падать, если исправления были
      # # Запуск форматтера (аналог `ruff format`).
      - id: ruff-format

  # -------------------------------------------------------------------------
  # Репозиторий Mypy для статической проверки типов.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        # Mypy требует, чтобы все зависимости были установлены, поэтому
        # `require_serial: true` гарантирует, что он будет запущен в окружении,
        # где они уже есть.
        require_serial: true
        # Передаем путь к нашему коду.
        args: [ "apps/" ]
        # Указываем pre-commit, что для работы этого хука
        # нужно установить дополнительные зависимости в его изолированную среду.
        additional_dependencies: [ "django-stubs==5.2.7" ]