# Generated by Django 5.2.7 on 2025-10-28 09:35

import apps.common.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁa-zA-Z\\s-]+$', message='Это поле может содержать только буквы, пробелы и дефисы.')], verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=100, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁa-zA-Z\\s-]+$', message='Это поле может содержать только буквы, пробелы и дефисы.')], verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Введите номер в любом удобном формате, включая международный.', max_length=20, null=True, validators=[apps.common.validators.validate_international_phone_number], verbose_name='Телефон')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('IN_PROGRESS', 'В работе'), ('CONVERTED', 'Конвертирован'), ('LOST', 'Потерян')], db_index=True, default='NEW', max_length=20, verbose_name='Статус')),
                ('ad_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='advertisements.adcampaign', verbose_name='Рекламная кампания')),
            ],
            options={
                'verbose_name': 'Потенциальный клиент',
                'verbose_name_plural': 'Потенциальные клиенты',
                'ordering': ['-created_at'],
            },
        ),
    ]
