# Generated by Django 5.2.7 on 2025-10-28 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialclient',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_leads', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер'),
        ),
        migrations.AddConstraint(
            model_name='potentialclient',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('email',), name='unique_active_lead_email'),
        ),
        migrations.AddConstraint(
            model_name='potentialclient',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('phone',), name='unique_active_lead_phone'),
        ),
    ]
