# Generated by Django 5.2.7 on 2025-10-10 07:43

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialclient',
            name='phone',
            field=models.CharField(blank=True, help_text='Введите номер в любом удобном формате, включая международный.', max_length=20, null=True, unique=True, validators=[apps.common.validators.validate_international_phone_number], verbose_name='Телефон'),
        ),
    ]
